# Generated by Django 4.0.5 on 2022-06-11 07:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_post_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='post_image'),
        ),
    ]
