# Generated by Django 4.0.5 on 2022-06-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_company_project_languages_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='project',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
