# Generated by Django 4.0.5 on 2022-06-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_username_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
