# Generated by Django 4.0.5 on 2022-06-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_rating_project_rating_rating_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rator',
        ),
    ]
